[General]
dns-server = https://doh.pub/dns-query,https://dns.alidns.com/dns-query,223.5.5.5
fallback-dns-server = system
ipv6 = false
dns-direct-system = false
private-ip-answer = true

[Rule]
RULE-SET,https://raw.githubusercontent.com/RickHuang2001/proxy-rules/main/rules/custom_reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/RickHuang2001/proxy-rules/main/rules/custom_proxy.list,PROXY
RULE-SET,https://raw.githubusercontent.com/RickHuang2001/proxy-rules/main/rules/custom_direct.list,DIRECT
GEOIP,CN,DIRECT
FINAL,PROXY